name: TorchBench Correctness Testing
on:
  workflow_dispatch:
env:
  PYTHON_VERSION: "3.8"
  CUDA_VERSION: "11.3"
jobs:
  run_test:
    if: ${{ github.repository_owner == 'pytorch' }}  && contains(github.event.pull_request.body, 'RUN_CORRECTNESS:') }}
    runs-on: [self-hosted, bm-runner-v100]
    timeout-minutes: 120 # 2 hours
    steps:
      - name: Checkout TorchBench
        uses: actions/checkout@v2
        with:
          path: benchmark
      - name: Checkout fx2trt
        uses: actions/checkout@v2
        with:
          repository: pytorch/fx2trt
          path: fx2trt
          token: ${{ secrets.TORCHBENCH_ACCESS_TOKEN }}
      - name: Checkout Torch-TensorRT
        uses: actions/checkout@v2
        with:
          repository: NVIDIA/Torch-TensorRT
          path: torch-trt
      - name: Checkout TorchDynamo
        uses: actions/checkout@v2
        with:
          repository: facebookresearch/torchdynamo
          path: torchdynamo